openapi: 3.0.0
info:
  version: 1.0.0
  title: Recipes API
  description: API for managing recipes
paths:
  /recipes/{id}:
    get:
      summary: Get a recipe
      operationId: getRecipe
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the recipe to retrieve
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        404:
          description: Recipe not found
        500:
          description: Internal server error
    put:
      summary: Update a recipe
      operationId: updateRecipe
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the recipe to update
      responses:
        200:
          description: Recipe updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        500:
          description: Internal server error
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jonatascb/recipes-api/1.0.0
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: string
        visitsCounter:
          type: integer